//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessTheNumber.Core.ErrorMessages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GuessTheNumber.Core.ErrorMessages.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All games already finished.
        /// </summary>
        public static string GuessTheNumberAllGamesAlreadyFinished {
            get {
                return ResourceManager.GetString("GuessTheNumberAllGamesAlreadyFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username or password incorrent.
        /// </summary>
        public static string GuessTheNumberCredentialIncorrent {
            get {
                return ResourceManager.GetString("GuessTheNumberCredentialIncorrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with this email address already exists.
        /// </summary>
        public static string GuessTheNumberEmailAlreadyExist {
            get {
                return ResourceManager.GetString("GuessTheNumberEmailAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error.
        /// </summary>
        public static string GuessTheNumberException {
            get {
                return ResourceManager.GetString("GuessTheNumberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User hasn`t created.
        /// </summary>
        public static string GuessTheNumberHasntCreated {
            get {
                return ResourceManager.GetString("GuessTheNumberHasntCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model is not valid.
        /// </summary>
        public static string GuessTheNumberModelIsNotValid {
            get {
                return ResourceManager.GetString("GuessTheNumberModelIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid token.
        /// </summary>
        public static string GuessTheNumberTokenInvalid {
            get {
                return ResourceManager.GetString("GuessTheNumberTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User doesn`t exists.
        /// </summary>
        public static string GuessTheNumberUserDoesNotExist {
            get {
                return ResourceManager.GetString("GuessTheNumberUserDoesNotExist", resourceCulture);
            }
        }
    }
}
